# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "my-s3-bucket-terraform-state"
    dynamodb_table = "terraform-lock"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "eu-west-1"
  }
}
